a=input("first number: ")
b=input("second number: ")
c=input("third number: ")
d=input("fourth number: ")
e=input("fifth number: ")
print("\n\n")
print("input your first number:",a)
print("input your second number:",b)
print("input your third number:",c)
print("input your fourth number:",d)
print("input your fifth number:",e)
print("float of",a,"Equal",float(a))
print("Complex of",a,"Equal",complex(a))
print("float of",b,"Equal",float(b))
print("Complex of",b,"Equal",complex(b))
print("float of",c,"Equal",float(c))
print("Complex of",c,"Equal",complex(c))
print("float of",d,"Equal",float(d))
print("Complex of",d,"Equal",complex(d))
print("float of",e,"Equal",float(e))
print("Complex of",e,"Equal",complex(e))